.TH "RPI-WIFI-AP" 1
.SH NAME
rpi-wifi-ap \- Easily start and stop using your Raspberry Pi as a wireless access point.

.SH SYNOPSIS
rpi-wifi-ap {start,stop,status}

.SH DESCRIPTION
Application that sets up a Raspberry Pi as a wireless access point.

By default, the SSID is the hostname of the machine that runs the script, and the default password is set based on the Raspberry Pi serial number.

The access point network configuration can be customized by editing defaults.conf (located in /etc/default/rpi-wifi-ap/defaults.conf); for example, setting up a different IP address for the network, the range of addresses that the DHCP server can lease, and the network SSID and passphrase.

This file is sourced in the main rpi-wifi-ap script, so you can use expresions that will be evaluated later on.


.SH OPTIONS

.TP
.B start
Use Raspberry Pi as wireless access point.

.TP
.B stop
Stop access point mode and restore previous configuration.

.TP
.B status
Display access point state and information.

.SH BUGS
No known bugs.

.SH AUTHOR
pi-top (deb-maintainers@pi-top.com)
